polysemy-research/polysemy

src/Polysemy.hs
src/Polysemy/Error.hs
src/Polysemy/Fixpoint.hs
src/Polysemy/Input.hs
src/Polysemy/Internal.hs
src/Polysemy/Internal/Combinators.hs
src/Polysemy/Internal/Effect.hs
src/Polysemy/Internal/Lift.hs
src/Polysemy/Internal/TH/Effect.hs
src/Polysemy/Internal/TH/Performance.hs
src/Polysemy/Internal/Tactics.hs
src/Polysemy/NonDet.hs
src/Polysemy/Output.hs
src/Polysemy/Random.hs
src/Polysemy/Reader.hs
src/Polysemy/Resource.hs
src/Polysemy/State.hs
src/Polysemy/Trace.hs
src/Polysemy/Writer.hs
test/FusionSpec.hs

Because nobody has time to type that shit out :)

Replace Semantic with Sem for easy typings

---

src/Polysemy/Internal/CustomErrors.hs

Mention polysemy-plugin in ambiguous effect error message.

---

polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/test/ExampleSpec.hs

Fixes #61; see the discussion there for what went wrong.

Fix the plugin

---

package.yaml
src/Polysemy/Internal/TH/Effect.hs
stack.yaml

This PR should resolve (at least) #56, #48 and add support for other variants of datatype declaration (even data families maybe?). See TODOs in code for things that need to be resolved.

Rewrite 'Polysemy.Internal.TH.Effect' in terms of 'th-abstraction'

---

src/Polysemy/Internal/TH/Effect.hs
test/ThEffectSpec.hs

(WIP)
Updates #76 with tests and small corrections.

Update smart constructors generation with tests and support for operators

---

polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/test/PluginSpec.hs

Perform recursive unification attempts in the plugin

---

ChangeLog.md
README.md
bench/Poly.hs
polysemy-plugin/test/ExampleSpec.hs
polysemy.cabal
src/Polysemy/Internal.hs
src/Polysemy/Resource.hs
test/BracketSpec.hs

https://github.com/isovector/polysemy/issues/73#issuecomment-500042179 pointed out that the `Resource` effect was missing a lot of things. This PR fixes that!

Better Resource bracketing

---

src/Polysemy/Internal/TH/Effect.hs

Use tySynInstDCompat for future compatibility with TH

---

.travis.yml

This PR has a travis config that will supposedly automate my release process.

Try to automate releases for polysemy

---

src/Polysemy/Input.hs

This was so disturbingly trivial, I feel like cheating :)
Fixes #122

Better runMonadicInput type order

---

polysemy.cabal
src/Polysemy/Internal/Combinators.hs
test/InterceptSpec.hs

Fix intercept not hoisting itself into embedded computations

---

src/Polysemy/Error.hs

Helpful things for using errors in real life

New error combinators

---

src/Polysemy/Output.hs
src/Polysemy/Trace.hs
test/OutputSpec.hs

Add runOutputAsList and a test for it

---

src/Polysemy/Async.hs
src/Polysemy/Internal/Forklift.hs

Remove some loopbreakers that were left around

---

src/Polysemy/IO.hs

runEmbedded lets you interpret a `Lift m` via some `forall x. m x -> IO x` by pretending all the other polysemy actions are in IO and using its `MonadIO` instance.
Fixes #137

Implement runEmbedded

---

polysemy-plugin/package.yaml
polysemy-plugin/polysemy-plugin.cabal
polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy.cabal
src/Polysemy/Internal/CustomErrors.hs
src/Polysemy/Internal/CustomErrors/Redefined.hs

Redefine Type.Errors directly in polysemy

---

ChangeLog.md
src/Polysemy/Error.hs
src/Polysemy/IO.hs
src/Polysemy/Reader.hs
src/Polysemy/State.hs

Change tyvar orders

---

polysemy.cabal
src/Polysemy/Writer.hs
test/WriterSpec.hs

Add Pass to Writer, replacing Censor. Fix semantics of listen

---

src/Polysemy/NonDet.hs

Now that `NonDet` is higher-order, this strikes me as an interpreter that may be useful in practice, for people that like to use `<|>` rather than the clunkier `catch`.

Add nonDetToError

---

package.yaml
polysemy.cabal
src/Polysemy/Internal/CustomErrors.hs
stack.yaml

Resolves #180
I hope it makes it easier to write and maintain messages of custom type errors.

[#180] Use type-errors-pretty package

---

src/Polysemy/Trace.hs

Fixes https://github.com/polysemy-research/polysemy/issues/189

GH-189 Fix typo in outputToTrace documentation

---

test/AsyncSpec.hs

This presumably fixes #195, but that issue warrants some further investigation

Have AsyncSpec use locks instead of sleeps

---

src/Polysemy/Internal/TH/Effect.hs

add DataKinds to the checkExtensions list

---

package.yaml
polysemy.cabal
src/Polysemy/AtomicState.hs
src/Polysemy/Output.hs
src/Polysemy/State.hs
src/Polysemy/Writer.hs
test/OutputSpec.hs
test/WriterSpec.hs

I haven't added any tests for `AtomicState` itself, tell me if you think they would be necessary.

Add AtomicState and atomic interpreters for Output/Writer

---

src/Polysemy.hs
src/Polysemy/Internal.hs
src/Polysemy/Internal/Union.hs

Add subsume operation, expose raiseUnder/2/3

---

ChangeLog.md
src/Polysemy/AtomicState.hs
src/Polysemy/Final.hs
src/Polysemy/Fixpoint.hs
src/Polysemy/Internal.hs
src/Polysemy/Internal/Writer.hs
src/Polysemy/Output.hs
src/Polysemy/State.hs
src/Polysemy/Writer.hs

I won't merge this yet in case I find something more (which I doubt).
@isovector Don't hesitate to merge this when you're ready to publish v1.2.

Fix mistakes in Final, add atomic/StateToIO

---

stack.yaml

Depend on newer type-errors-pretty

---

polysemy.cabal
src/Polysemy/Error.hs
test/ErrorSpec.hs

Been thinking about how to write good real life code with polysemy --- realized this thing was conspicuously missing.

Add fromException and fromExceptionVia

---

polysemy.cabal
src/Polysemy/Tagged.hs
src/Polysemy/View.hs
test/ViewSpec.hs

I was looking for an excuse to try out the new `Tagged` stuff, so I ported one of the effects I find myself continually writing. `View` is for for automatically caching an expensive computation over a `State`.
(depends on #223)

View effect

---

package.yaml
polysemy.cabal
src/Polysemy/Law.hs
src/Polysemy/State/Law.hs
test/LawsSpec.hs

This PR adds machinery for writing easy laws that should hold for an effect. It gives an example of what they'd look like for `State s`.
Fixes #266

Law Machinery

---

src/Polysemy/NonDet.hs
test/AlternativeSpec.hs

See #246 
all around me are familiar faces

Revert functorial state of runNonDet to []

---

package.yaml
polysemy.cabal
test/FusionSpec.hs

Feel free to revert when everything is fixed upstream!

Disable loopbreaker

---

src/Polysemy/Trace.hs

Update outputToTrace definition

---

src/Polysemy/Error.hs

Error utility

---

stack.yaml

Update the resolver

---

package.yaml

Bump bounds for first-class-families

---

src/Polysemy/Internal/Writer.hs
src/Polysemy/Output.hs
src/Polysemy/Writer.hs
test/WriterSpec.hs

Closes #310.
How would you go about creating tests for this? Something like "`take 100 . fst . run . runLazyOutputList $ forever (output ())` must terminate within 2 seconds?"

Add lazy interpretations for Output and Writer

---

package.yaml
polysemy.cabal
stack.yaml

Fixes https://github.com/commercialhaskell/stackage/issues/5237

Relax `first-class-families` bounds

---

src/Polysemy/Resource.hs

Add bracket_ to Polysemy.Resource

---

package.yaml
polysemy.cabal

update github org

---

src/Polysemy/Internal.hs

I assume this isn't some magic trick.

correct two switched INLINE pragmas

---

polysemy-plugin/ChangeLog.md
polysemy-plugin/package.yaml
polysemy-plugin/polysemy-plugin.cabal

This is a simple version bump and changelog addition, to fix issue #336. I can rebase if this isn't uploaded today.

polysemy-plugin v0.2.5.1

---

polysemy.cabal

Builds fine and all tests pass here.

Allow th-abstraction 0.4

---

ChangeLog.md
package.yaml
polysemy.cabal

Please make sure that I haven't missed any breaking changes (so that we bump version properly).

Release 1.4.0.0

---

polysemy-plugin/ChangeLog.md
polysemy-plugin/package.yaml

Corresponding to `polysemy-1.4.0.0` release.

Release plugin 0.2.5.2

---

ChangeLog.md
src/Polysemy/Internal.hs
src/Polysemy/Internal/Bundle.hs

add InterpretersFor

---

polysemy.cabal

Builds fine and all tests pass.

Allow doctest 0.17 and 0.18

---

ChangeLog.md
src/Polysemy/Trace.hs

Add traceToStdout and traceToStderr, deprecating traceToIO

---

package.yaml
polysemy-plugin/package.yaml
polysemy-plugin/src/Polysemy/Plugin.hs
polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/src/Polysemy/Plugin/Fundep/Stuff.hs
polysemy-plugin/src/Polysemy/Plugin/Fundep/Unification.hs

Wasn't sure which branch to merge into since #410 is already open.
I think that if this PR is merged we can just merge ghc9 into master.

add ghc9 support for polysemy-plugin

---

ChangeLog.md
polysemy-plugin/polysemy-plugin.cabal
polysemy-plugin/test/InsertSpec.hs
polysemy-plugin/test/TypeErrors.hs
polysemy.cabal
src/Polysemy.hs
src/Polysemy/Bundle.hs
src/Polysemy/Internal.hs
src/Polysemy/Internal/Bundle.hs
src/Polysemy/Internal/Index.hs
src/Polysemy/Internal/Kind.hs
src/Polysemy/Internal/Sing.hs
src/Polysemy/Internal/Union.hs

Add combinator for adding effects at an index

---

README.md

Was searching for exactly this and today stumbled upon on reddit. I think it's a useful resource to link to given that mtl is *the* monad stacking library around, especially for those who aren't deep into effect libraries.

Add link to "Porting to Polysemy"

---

package.yaml
polysemy.cabal
src/Polysemy/Internal/Scoped.hs
src/Polysemy/Scoped.hs

note: adds `BlockArguments`, which should be fine since we dropped 8.4.4

add Scoped

---

polysemy.cabal

Builds fine and all tests pass.

Allow doctest 0.19

---

polysemy.cabal

Builds fine and all tests pass.

Allow inspection-testing 0.5

---

polysemy-plugin/polysemy-plugin.cabal
polysemy.cabal
src/Polysemy/Internal.hs
src/Polysemy/Internal/Combinators.hs
src/Polysemy/Internal/Scoped.hs
src/Polysemy/Scoped.hs
stack.yaml

WIP cleanups to #455 and #456. Will be continually added upon. Keeping them separate so we can discuss if there's any change you have questions about or disagree with.

Extend Scoped

---

src/Polysemy/Internal/Union.hs

At Wire we're running into insane compilation times / memory usage when trying to build polysemy-heavy modules. Upon thinking, we don't actually want to inline `membership'` proofs; the only reason to do so would be if they're immediately given to `decomp`, which is the only elimination form for them. Unfortunately, I don't think this can ever happen.
Instead what happens is we inline big membership terms everywhere they're used. I don't think this is the issue, but the resulting code-bloat is. Every one of these terms needs to be typechecked and traversed and have type applications everywhere in core, which generates a lot more work for GHC.
In addition, GHC probably knows better than we do whether or not these things should be inlined, so I've marked them as `INLINABLE` instead of …

Saner defaults for union inlining

---

flake.lock
flake.nix
nix/overlay.nix
package.yaml
polysemy-plugin/package.yaml
polysemy-plugin/polysemy-plugin.cabal
polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/src/Polysemy/Plugin/Fundep/Unification.hs
polysemy.cabal

needs https://github.com/isovector/type-errors/pull/7

support GHC 9.6

---

package.yaml
polysemy.cabal

Allow th-abstraction 0.6
