bench/countDown.hs
package.yaml

The [blog post](https://reasonablypolymorphic.com/blog/too-fast-too-free/) displays some benchmarks, but I couldn't reproduce the numbers in the blog post. Here is my recreation of your benchmark, following [our reddit discussion](https://www.reddit.com/r/haskell/comments/as1anb/freer_monads_too_fast_too_free_reasonably/egzn1je/). Could you let me know if my benchmarking code differs from yours?

add a benchmark

---

package.yaml

too-fast-too-free was compiled without -O2, which put it at a
disadvantage compared to the code from the competing libraries, which is
inside the benchmark project and was thus compiled with -O2.

fairer benchmark with -O2 for everyone

---

src/Polysemy/Error.hs
src/Polysemy/Input.hs
src/Polysemy/Internal/Combinators.hs
src/Polysemy/Internal/Effect.hs
src/Polysemy/Internal/Tactics.hs
src/Polysemy/Internal/Union.hs
src/Polysemy/Output.hs
src/Polysemy/Random.hs
src/Polysemy/State.hs
src/Polysemy/Writer.hs

@glaebhoerl [asked](https://twitter.com/glaebhoerl/status/1119606664762658819) what the Typeable constraints were for, I tried to delete a few so that the compiler errors would give me the answer, and was surprised to discover that most of the Typeable constraints are actually redundant!
I recommend adding `-fwarn-redundant-constraints` to your `ghc-options`, it reveals even more redundant constraints.

Redundant typeable

---

src/Polysemy.hs
src/Polysemy/Internal.hs

When having many effects in one function, type signatures tend to get hard to read. I am proposing adding two new type synonyms - `Members`, which takes list of effects instead of one and `(>@>)` (_at-fish_ or whatever you want to call it :smile:), which constructs type from list of member effects and return type:
```haskell
foo :: ( Member (Output Int)  r
, Member (Output Bool) r
, Member Console       r
)
=> Sem r ()
```
could be written simply as:
```haskell
foo :: '[Output Int, Output Bool, Console] >@> ()
```
There are few things I am not completely sure about:

Add Members and (>@>) type synonyms

---

README.md

For the purpose of getting new users off on the right foot immediately, I added the necessary pragmas to get these working, and built out a trivial example of how to actually use `runConsoleIO`. I wanted to write something like `runConsoleBoring` as an example of mocking using `Input` and `Output` maybe(?), but I wasn't sure how to go about it. I also haven't tried writing a `Resource` example, yet.

Extend examples, make them easy to copy and paste

---

src/Polysemy/Internal/Union.hs

I am not sure if it "erases" as well as the `Typeable` version, because looking at it:
`prj` is used only in `interceptH`
`interceptH` is used only in `intercept` (and exported)
`intercept` is never never used internally, only exported, i.e. none of this is tested.
I would be happy to write some tests, if you have any suggestions/guidelines. (this is the `WIP` part of the PR)
The only thing that is getting called is `weaken`, which is the same as before, except freed from having to provide a `Typeable` context.

Replace Typeable with SNat equality

---

src/Polysemy/Internal/Combinators.hs
src/Polysemy/Internal/CustomErrors.hs
src/Polysemy/Internal/Effect.hs
src/Polysemy/Internal/Tactics.hs
src/Polysemy/Internal/Union.hs

Addresses #29 by implementing the [workaround used by `fused-effects`](https://github.com/fused-effects/fused-effects/blob/4d0e056c95e4016d6c8d8e14909702874e17863a/src/Control/Effect/Carrier.hs#L16) that @patrickt suggested.

Support versions of GHC without QuantifiedConstraints

---

README.md

This is meant to address issue #27 
In addition to documenting where to add polysemy-plugin I also changed the second example to not require it. The motivation being that documentation for polysemy-plugin can be in one place and there'd be no need to add a caveat near the resource-effect example that polysemy-plugin must be installed.

polysemy-plugin doc

---

ChangeLog.md
polysemy-plugin/package.yaml
polysemy-plugin/src/Polysemy/Plugin.hs
polysemy-plugin/src/Polysemy/Plugin/InlineRecursiveCalls.hs
polysemy-plugin/src/Polysemy/Plugin/Phases.hs
polysemy-plugin/test/InlineRecursiveCallsSpec.hs
src/Polysemy.hs
src/Polysemy/Internal/TH/Performance.hs

Previously there was a TH method `inlineRecursiveCalls` that would break self-recursion into mutual-recursion and add some janky inlining properties to convince the inliner to simplify things.
The TH was unpleasant, in that it would prevent people from writing haddock for their interpreters --- and that it was a thing people needed to think about in the first place.
This PR adds a CoreToDo pass to make the same transformation directly in the core representation. It also adds the additional optimization passes necessary to get GHC to inline interpreters away.

Automatically inline recursive calls in the plugin

---

package.yaml
polysemy.cabal
src/Polysemy/Internal.hs
src/Polysemy/Internal/Combinators.hs
src/Polysemy/Internal/Union.hs
test/HigherOrderSpec.hs

#57 pointed out that `local` doesn't work in `Reader`. Some investigation showed that `runReader` was not to blame. Uh oh!
The bug was something stupid; when I introduced the `Tactics` machinery I didn't retest my original interpreters; and instead was relying on the typesystem. But the implementation of `interpretH` and friends would hard-code the current interpreter into the natural transformation in `Tactics`, which meant that the signature for `runT` et al was lying. They promised to give you some effects you could handle, but in fact _they were already handled!_
I've fixed the bug and added a small test case to prove `local` now works.

Fix broken higher order effects

---

README.md

I left that in when writing the README example because I use a custom Prelude. Whoops.

Remove erroneous Prelude import

---

polysemy-plugin/test/InlineRecursiveCallsSpec.hs
polysemy.cabal
src/Polysemy.hs
src/Polysemy/Error.hs
src/Polysemy/Internal.hs
src/Polysemy/Internal/Combinators.hs
src/Polysemy/Internal/Effect.hs
src/Polysemy/Internal/Tactics.hs
src/Polysemy/Internal/Union.hs
src/Polysemy/NonDet.hs
src/Polysemy/State.hs
test/InspectorSpec.hs

GetInspectorT

---

polysemy-plugin/polysemy-plugin.cabal

The test suite is made for 0.3 and doesn't compile with earlier versions due to Yo now taking another argument since https://github.com/isovector/polysemy/pull/71

Update polysemy-plugin version bound

---

polysemy-plugin/package.yaml
polysemy-plugin/polysemy-plugin.cabal
polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/test/BadSpec.hs
polysemy-plugin/test/PluginSpec.hs

This is a fix for the "solveSimpleWanteds: too many iterations" problem
that people are running into. In these cases, the plugin is being asked
to solve the same `Member` constraint several times, and generating
a new wanted each time. In doing so, GHC thinks that work was done, so
it will ask the plugin to run again next time. This process diverges,
and produces the error.
Fixes #79

Ensure wanted constraints are emitted only once.

---

polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/test/PluginSpec.hs

The plugin used to choke on this:
```haskell
flipShouldBe 11 . sum . fst . run . runFoldMapOutput id $ do
output [1]
output $ replicate 2 5
```
because it would fail to unify `Output (t Int)` (the polymorphic `Traversable` variable in `sum`) with `Output [Int]`.
In this case, there are no given constraints, so the plugin is attempting to solve a `Member (Output (t Int)) '[Output [Int]]`. We reuse the codepath for unifying wanted/givens, pretending like the
`Output (t Int)` is a given.[^1]
[^1]: Pretending it's a wanted breaks the common case of trying to call, eg. `runState (5 :: Num a => a)`  on an effect `State Int`.
So now we have a "wanted" `Output [Int]`, and a "given" `Output (t Int)`. In general, this thing isn't OK to solve. Consider a real example:
```haskell
foo :: Member …
```

Allow bidirectional typechecking in the plugin

---

package.yaml
polysemy.cabal
src/Polysemy/Internal/CustomErrors.hs
stack.yaml
test/DoctestSpec.hs

This PR introduces the FCF machinery that will give us more control over writing type-level functions. It defines an `IfStuck a b c` tyfam that will leave `b` around if `a` is stuck, otherwise it will fcf-evaluate `c`. Everything is polykinded so we can stack these things together to make big logic chains to emit specific variables depending on what exactly is stuck.
Fixes #106

Don't emit the FirstOrder error for unknown effects

---

.gitignore
.travis.yml
cabal.project
package.yaml
polysemy.cabal
stack.yaml

Changes:
- add `cabal.project` to let `cabal v2-*` commands know about `polysemy-plugin`
- also provides some nice `ghc-options` that should speed up compilation (just slightly)
- drops `transformers` lower bound to `0.5.2.0` (which is what it looks like GHC 8.2.2 ships with)
- adds `.ghc.environment` and `dist-newstyle` files to the `.gitignore` since the new `cabal` makes these files and they're annoying
- bumps `stack` LTS to 13.25 to pull in GHC 8.6.5 since that's the latest version of the GHC 8.6 release train
- bumps GHC version in the Travis test matrix
---
Running `cabal v2-build` works for both `polysemy` and `polysemy-plugin` for GHC 8.2.2 -> GHC 8.6.5, but running `cabal v2-test polysemy-plugin` fails for GHC 8.2.2 with the following error:
<details><summary>Error Log …

Trying to fix some Travis stuff

---

package.yaml
polysemy-plugin/package.yaml
polysemy-plugin/polysemy-plugin.cabal
polysemy.cabal
src/Polysemy.hs
src/Polysemy/Internal/Forklift.hs
src/Polysemy/Internal/Kind.hs
src/Polysemy/Internal/Union.hs
stack.yaml

#126 is finished, but big. Instead I'm splitting it up into a few PRs.
@ocharles pointed out that my brilliant idea for solving the "run state underneath IO effects" solution already has a name --- [the forklift](https://apfelmus.nfshost.com/blog/2012/06/07-forklift.html).
This PR provides a single function `withLowerToIO`, which runs a desired `Sem r` effect all the way down to `IO`, without needing to know the natural transformation beforehand. It does it by running the desired code in a new thread, and shipping all of the unhandled effects back to the main thread. The main thread turns into an event loop for the duration of the `withLowerToIO` block.

Forklift interpretations

---

src/Polysemy/Internal/CustomErrors.hs
src/Polysemy/Internal/TH/Common.hs
src/Polysemy/Internal/Union.hs
test/TypeErrors.hs

This shuffles around the error messages so they are only connected to code generated via `makeSem`. This means that badly-typed interpreters will no longer set off the eager error messages!
Also it uses the newish `IfStuck` machinery, which just happens to fix #89. And I added a test for #136

Improved errors

---

src/Polysemy/Internal/CustomErrors.hs
src/Polysemy/Internal/Union.hs
test/TypeErrors.hs

When emitting messages for ambiguous sends: use `IfStuck` on `r` to
determine if we can compose it. This means `r` is in one of three
states, stuck, cons or nil. We want to wrap it in parentheses iff it's
a cons.
Fixes #74

Parenthesize r when it's a cons

---

.gitignore
polysemy-plugin/package.yaml
polysemy-plugin/polysemy-plugin.cabal
polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/test/DoctestSpec.hs
polysemy-plugin/test/TypeErrors.hs
src/Polysemy/Internal/Union.hs
test/TypeErrors.hs

This PR changes the plugin so it will notice an insoluble constraint of the form `Sem r a ~ Foo`, and mark that `r` takes part in a genuine type error. The plugin will then provide a bogus evidence term for `IfStuck (IndexOf r _) _ _`, which prevents the `AmbiguousSend` error message from firing.
Fixes #136 and #108

Don't emit ambiguous effect errors for genuine type errors

---

src/Polysemy/Output.hs
test/OutputSpec.hs

Addresses #112 
This function now transforms an `Output o` into `Output [o]`, which only outputs elements once the specified number of `o`'s have been collected. The only exception is the last element which contains the rest (if any).

Improve runBatchOutput

---

src/Polysemy/Error.hs
src/Polysemy/IO.hs
src/Polysemy/Internal.hs
src/Polysemy/Internal/Combinators.hs
src/Polysemy/Internal/Tactics.hs
src/Polysemy/Internal/Union.hs
src/Polysemy/NonDet.hs
src/Polysemy/State.hs
test/FusionSpec.hs

The name `Yo` is objectively terrible. I changed it, and added some documentation.
Fixes #159

Rename Yo ==> Weaving

---

.travis.yml
package.yaml
polysemy.cabal
test/FusionSpec.hs

Turns out haddocks have been broken forever, but because of https://github.com/haskell/cabal/issues/5977 we never noticed. This PR fixes CI so it breaks (see 6f915b6), and then fixes it by changing the GHC versions under which we're allowed to use loopbreaker. Fixes #160

Don't use Loopbreaker until GHC 8.7+

---

src/Polysemy/Writer.hs

I forgot to add those wacky `INLINE` pragmas...

Add inlining to Polysemy.Writer

---

src/Polysemy/Internal.hs
src/Polysemy/Internal/NonDet.hs
src/Polysemy/NonDet.hs
test/AlternativeSpec.hs

`Alternative` is typically used for simple exception handling a la "try-otherwise". However, `NonDet` is too weak in its current form to write interpreters for it that actually skip effects of the second branch. The solution to this is to make `NonDet` higher-order.
I also chose to represent `Choose` through embedding the two branches directly, as `Bool -> m a` is isomorphic to `(m a, m a)`, and the latter formulation is _probably_ more efficient.
This does not actually break anything - you can still write `runNonDet` with the same semantics as before (although my implementation could possibly be less efficient).
But now you can also write interpreters like `runNonDetMaybe`, which skips local effects (i.e. effects whose interpreters have already been run) of the second branch if the first …

Make NonDet Higher-Order

---

src/Polysemy/Trace.hs

It just doesn't need to be there

Remove redundant constraint from ignoreTrace

---

src/Polysemy/Internal.hs
test/DoctestSpec.hs

Fixes #127.
Does `resourceToIO` need any more documentation?

Document change in semantics based on order of interpreters

---

src/Polysemy.hs
src/Polysemy/Async.hs
src/Polysemy/IO.hs
src/Polysemy/Internal/Forklift.hs
src/Polysemy/Internal/Union.hs
src/Polysemy/Resource.hs

This simplifies the `Forklift` machinery, and removes the need for `LastMember`.
Note that this is a breaking change, which is a bit of a shame seeing how we just released v1...
This closes #183

Simplified Forklift machinery, remove `LastMember`

---

polysemy.cabal
src/Polysemy/Fixpoint.hs
test/FixpointSpec.hs

I stumbled across this interesting improvement to the semantics of `Fixpoint` interpreters.
The big problem with the current interpreters of fixpoint is that they diverge if any distribution law `forall x. f (m x) -> Sem r (f x)` of any `Weaving` is strict in the functorial state, which they pretty much _always are_ if you have run any return-value changing interpreter such as `runState` and `runError`.
However, it's possible to improve upon this by taking cues from the `MonadFix` implementations of `StateT` and `ExceptT`. Instead of using the recursive functorial state, we could use the initial state. Because of this, we need to extract the encapsulated value of the recursive state in order to have something to provide to the function. We can do that using the inspector, inserting a …

Improve semantics of Fixpoint

---

src/Polysemy/Output.hs

Adds a `runOutputSem` interpreter, which runs a monadic action over each output value. Similar to `runInputSem` for `Input`
Not sure if it belongs in the library (it feels _too simple_, like runInputSem does), but [I've found it useful in my projects](https://github.com/cnr/discord-hs/blob/6983b4f545aa883fe3515432377bdc4da08789eb/src/Discord/Gateway.hs#L126-L127)

Add runOutputSem interpreter

---

src/Polysemy/Internal/Combinators.hs
src/Polysemy/Output.hs
src/Polysemy/State.hs
src/Polysemy/Writer.hs
test/OutputSpec.hs
test/WriterSpec.hs

This closes #192 and closes #193

Fix strictness semantics of State and Writer

---

src/Polysemy/Output.hs
src/Polysemy/Writer.hs

`runOutputMonoid` and `runWriter` combine the monoidal values left-associatively, which results in terrible performance when used together with linked lists such as `String`. This can be addressed by instead using `DList a`/`Endo [a]` as the monoid, which, through some CPS magic, effectively "right-associates" uses of `<>`, making lists behave asymptotically better.
I figured we could add interpreters that automate the conversions between a monoid and its `Endo` variant, and therefore do all this wrangling under the hood, so that's what this pull request is about.
Right now, the interpreters are called `runOutputMonoidAssocR` and `runWriterAssocR`, which I don't particularly like. Does anyone have suggestions for better names?

Add right-associative variants of runOutputMonoid and runWriter

---

ChangeLog.md
src/Polysemy/Fixpoint.hs
src/Polysemy/Internal/Fixpoint.hs

I accidentally exported the `bomb` in `Polysemy.Fixpoint`, so this moves it to the internal module.
I also fixed some minor errors in the changelog of v1.

Hide visibility of Polysemy.Fixpoint.bomb, fix changelog

---

ChangeLog.md

It becomes increasingly obvious to me rather than doing a simple twice-over before I create pull requests, I should do quadruple-overs so I can catch dumb stuff like this.

Add `modify'` to changelog

---

src/Polysemy.hs
src/Polysemy/Fixpoint.hs
src/Polysemy/Internal.hs
src/Polysemy/NonDet.hs

I discovered while working on polysemy-zoo that `runNonDet` plays really badly with `Cont`, no matter how `Cont` is interpreted.
Consider this example, using the most reliable interpreters available (this uses https://github.com/polysemy-research/polysemy-zoo/pull/45):
```haskell
knot :: Member (Cont ref) r => a -> Sem r (a, a -> Sem r b)
knot a = callCC $ \c -> let b x = c (x, b) in pure (a, b)
bad :: IO [Int]
bad = do
ref <- newIORef []
_ <-  (`runContT` pure)
. runFinal
. embedToFinal
. embedToMonadIO
. contToFinal
. runOutputMonoidIORef ref (:[])
. runReader ()
. runNonDet @[]
$ do
(end, (i, loop)) <- local id $ ((,) 10 <$> knot 1) <|> ((,) 8 <$> knot 2)
output i
when (i < end) $
loop $! i + 1
readIORef ref
```
Without the `local id`, this does what you'd expect: return …

Improve choice of functorial state for runNonDet

---

README.md

I added a link to an article series on Raghu Kaippully's blog. For me at least it, somewhere in the limbo between books and actually writing production Haskell code, it was a very clear introduction.
I don't know if this needed to be a pull request or just an issue.

Add tutorial link in README.md

---

polysemy-plugin/ChangeLog.md
polysemy-plugin/package.yaml
polysemy-plugin/polysemy-plugin.cabal
polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/test/MultipleVarsSpec.hs

This is the improvement I described in #219. 
Any other improvements may be a long way off, if I even find a way to do them, so I figured I'd open this pull request separately for the easy fix.

polysemy-plugin: Reject ununifiable effect candidates early

---

src/Polysemy.hs
src/Polysemy/Internal.hs

Hi,
This PR tackles issue #220 . I've put the type synonym on the Polysemy.Internal module and documented it.
Please let me know if I should improve anything.

Add type synonym 'InterpreterFor' and documentation

---

polysemy-plugin/polysemy-plugin.cabal
polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/src/Polysemy/Plugin/Fundep/Stuff.hs
polysemy-plugin/src/Polysemy/Plugin/Fundep/Unification.hs
polysemy-plugin/test/BadSpec.hs
polysemy-plugin/test/HistorySpec.hs
polysemy-plugin/test/SpecificitySpec.hs
src/Polysemy/Internal/Union.hs

This thing solves #219, #209, and #114 I am pretty sure. 
In interpreter mode, the plugin used to see rows like `State (Identity a) ': State a ': r`, with an action in `State a`, and then _incorrectly unify that thing with the first thing in the list `State (Identity a)`_. As a result, we'd ask for `Identity a ~ a`, which is infinite, and things would go wrong.
Now we instead collect all of the unifications we'd like to do, and only emit _the most specific one,_ as measured by number of type constructors in it. This will now only emit a `State (Identity a) ~ State (Identity s)`, and then unify the state we're looking for, plus the `a ~ s` that solves the other state action.
But the next problem is that we can't determine `IndexOf` in the row above, because `a` is a type variable, and so …

Let plugin solve stuck type rows + bug fixes in interpreter mode

---

src/Polysemy/AtomicState.hs

Is there something wrong with having this?
Notably right now the "get" operation is atomic, but the function application isn't. I think this is the expected/desirable behaviour? Or should we go the other way around and have the function also be "atomic" by doing `snd <$> atomicState (id &&& f)`?

Add a convenience atomicGets

---

.travis.yml
Setup.hs
polysemy-plugin/Setup.hs
polysemy-plugin/polysemy-plugin.cabal
polysemy-plugin/test/DoctestSpec.hs
polysemy.cabal
stack.yaml
test/DoctestSpec.hs

Just a WIP so I can hit the CI on behalf of @googleson78 and https://github.com/polysemy-research/polysemy/pull/258

Feature/cabal doctest and ghc 8.8.1

---

src/Polysemy/Trace.hs

Adding an explicit quantifier as requested on this comment https://github.com/polysemy-research/polysemy/pull/289#issuecomment-560953740 by @isovector

Add explicit quantifier for parameters on outputToTrace

---

src/Polysemy/State.hs

This addresses #294. One remaining question: is reading and then writing `IORef`/`STRef`s any faster than calling `modifyIORef`/`modifySTRef` or their strict counterparts? If it offers performance speedups we may want to directly interpret `modify`.

Add runStateSTRef and stateToST

---

stack.yaml

Thanks to #298 there are now some new things in our resolver, so we can remove them from `extra-deps`
Notably this bumps the following libraries:
* aeson: 1.4.3.0 -> 1.4.6.0
* bifunctors: 5.5.4 -> 5.5.6
* inspection-testing: 0.4.2 -> 0.4.2.2
* th-abstraction: 0.3.1.0 -> 0.3.1.0@rev:1

Remove extra-deps that are now in resolver

---

stack.yaml

Unknowingly removed it in #299

Bring back monadLib with a clarification comment

---

README.md

[Rendered](https://github.com/srid/polysemy/blob/patch-1/README.md#polysemy)
Funprog zulip has a dedicated stream for Polysemy where a number of discussions are taking place. Sandy is participating as well. So why not make it the official chat for the project?
https://github.com/srid/rib also uses it.

Add zulip badge

---

.travis.yml
polysemy-plugin/src/Polysemy/Plugin.hs
polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/src/Polysemy/Plugin/Fundep/Unification.hs

Fixes #336 
* Ct (and friends) now comes from Constraints
* There was an ifdef'd part that uses a function "bool" which isn't imported when the ifdef triggers

Build with 8.10

---

src/Polysemy/Async.hs

I thought this may come in handy.

Added ability to cancel running Async actions

---

ChangeLog.md

Mostly concerned with moving them to the top of the changelog, so you can't easily miss them.
Also added one new thing to the section.

Move unreleased changes

---

src/Polysemy.hs
src/Polysemy/Internal.hs

These combinators are like raiseUnder, but place the new effect at the
second and third position in the list.
This is for interpreters that consume two effects, delegating to two other interpreters, who share a dependency which is then interpreted by the outer interpreter.
Please advise on what else to do, naming, general sense and so on!

raise2Under and raise3Under

---

src/Polysemy.hs
src/Polysemy/Internal.hs

See https://funprog.srid.ca/polysemy/raiseunder-and-multiple-effect-interpretation.html and #369.

Add 'Raise' and 'Subsume'

---

polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/src/Polysemy/Plugin/Fundep/Utils.hs
src/Polysemy/Async.hs
src/Polysemy/IO.hs
src/Polysemy/Input.hs
src/Polysemy/Internal.hs
src/Polysemy/Internal/Combinators.hs
src/Polysemy/Internal/Strategy.hs
src/Polysemy/Internal/TH/Common.hs
src/Polysemy/Internal/TH/Effect.hs
src/Polysemy/Internal/Union.hs
src/Polysemy/Internal/Writer.hs
src/Polysemy/NonDet.hs
src/Polysemy/State.hs
src/Polysemy/Writer.hs
test/FixpointSpec.hs

These are all replacements of the form
before: fmap f $ x
after:  f <$> x
Minor change, but feels marginally easier to read to me.

Small code simplifications

---

src/Polysemy/Internal.hs

Add Applicative `liftA2`, `(<*)`, and `(*>)` as directed in issue https://github.com/polysemy-research/polysemy/issues/368 .

add Applicative methods

---

ChangeLog.md
polysemy.cabal
src/Polysemy.hs
src/Polysemy/Internal/Combinators.hs
src/Polysemy/Internal/Tactics.hs
test/TacticsSpec.hs

A modified variant of @tek's [simple `runT` and `bindT` implementation](https://github.com/tek/polysemy/commit/36325a2027c66de5eec8b1b9548eb3bd992f8645). In comparison, this version:
- Doesn't require any extra type variables
- Allows the new combinators to also be used in `reinterpretHn`, and not just in `interpretH`
- Calls the combinators `runTH` and `bindTH` instead of `interpretHO` and `interpretBindHO`.
This partially adresses #386.
These names of `runTH` and `bindTH` still aren't final unless we want them to be.

Simple variants of runT and bindT

---

src/Polysemy/Internal.hs

I don't feel strongly about this change, but I frequently use these lifted `Monoid` and `Semigroup` instances in my own coding
I also wasn't sure what `@since` annotations to add since I don't know what the next release number will be.

Add `Semigroup` and `Monoid` instances for `Sem`

---

ChangeLog.md
src/Polysemy/AtomicState.hs

While `AtomicState` and `State` can't be merged, at least it should be made more accessible and clear that it is a superstructure.
Naming?

add runAtomicStateLocal

---

src/Polysemy/Internal/Union.hs

This PR implements `ElemOf` as an (unsafe) newtype around `Int`, and then does some pattern-synonym trickery to re-expose the safe `Here`/`There` constructors.
In the real world, this is a significant improvement in polysemy's code generation. When building `Galley.API.Public` from https://github.com/wireapp/wire-server/pull/1917, this change is:
```diff
- terms: 16,086
+ terms: 13,280
- types: 7,910,353
+ types: 6,465,139
- coercions: 13,919,222
+ coercions: 13,522,063
- ppr core size: 951956810
+ ppr core size: 949201550
```
Fixes #427

Implement ElemOf as an integer tag

---

polysemy-plugin/src/Polysemy/Plugin/Fundep.hs
polysemy-plugin/src/Polysemy/Plugin/Fundep/Unification.hs
polysemy-plugin/test/AmbiguousSpec.hs

This PR fixes a regression in #423 where the skolem set was being incorrectly created for interpreter-mode wanted constraints, leading to bad unifications.

Fix a regression in the plugin where polymorphic given effects in interpreters could unify

---

flake.lock
flake.nix
nix/overlay.nix
polysemy-plugin/src/Polysemy/Plugin/Fundep/Stuff.hs
polysemy-plugin/src/Polysemy/Plugin/Fundep/Unification.hs
polysemy-plugin/test/TypeErrors.hs
src/Polysemy/Internal/CustomErrors.hs
src/Polysemy/Internal/Index.hs

Caveat: The custom type error for `insertAt` has been disabled for this version since there appears to have been introduced a subtle change in the types used to match `InsertAtIndex` constraint, causing the incoherent instances to break.
Since the custom error feature isn't required for `insertAt` to work, I propose to postpone the fix for this.
Incorporates @spacekitteh's PRs #432 and #433.

Support GHC 9.2

---

src/Polysemy.hs
src/Polysemy/Internal.hs

We've previously remarked that we _really_ shouldn't have `send` be internal. Too many times. I decided I wouldn't forget it this time around.
Also cleaned up the documentation a bit. The review pass is mostly for that.

Expose `send`

---

ChangeLog.md
src/Polysemy/Error.hs
stack.yaml
test/ErrorSpec.hs

This hopefully fixes #444. I'm unexperienced with Polysemy's HO interpretation mechanism so I'm not sure if I impelemented this correctly; specifically I used `getInspectorS` and I'm unsure what to do at the `Nothing` case. It did pass the test in #444 though.

Prevent `errorToIOFinal` from mixing errors up (#444)

---

src/Polysemy/Internal/TH/Effect.hs

Uses new `putDoc` functionality to add documentation from constructors to generated functions. This may make it more practical to not expose original constructors at all.

Copy docs of effect constructors to functions

---

src/Polysemy/Tagged.hs

https://hackage.haskell.org/package/polysemy-1.7.1.0/docs/Polysemy-Tagged.html#v:tag
Currently:
With this commit:

Fix formatting issue in 'tag' documentation

---

package.yaml
polysemy-plugin/package.yaml
polysemy-plugin/polysemy-plugin.cabal
polysemy.cabal
src/Polysemy/Internal/Scoped.hs
src/Polysemy/Scoped.hs
test/ScopedSpec.hs

Since the `*With` interpreter uses `error` for the case that `Run` is encountered without a wrapping `InScope`, I realized that this would allow the resource to be visible in the interpreter only.
What do you think, @KingoftheHomeless @googleson78 ?
Bit awkward for sure, but not having to haul that parameter around everywhere would certainly be quite the increase in ergonomics.

Scoped without resource param

---

polysemy-plugin/polysemy-plugin.cabal
polysemy.cabal
src/Polysemy/Internal/Scoped.hs
src/Polysemy/Opaque.hs
src/Polysemy/Scoped.hs
test/ScopedSpec.hs

The big question here is the `Opaque` pollution, which is breaking. There _is_ a way around that if we _desperately_ want to avoid it, but it won't be forward compatible with my Vision Of The Future Of `Scoped`, where `runScopedNew` (or something in its like) will be the primary `Scoped` interpreter.

Fix scoped within scoped incoherency. Add `runScopedNew`

---

ChangeLog.md
polysemy-plugin/polysemy-plugin.cabal
polysemy.cabal
src/Polysemy/Internal/Scoped.hs
src/Polysemy/Opaque.hs
src/Polysemy/Scoped.hs
test/ScopedSpec.hs

@KingoftheHomeless can you explain why this fails? Shouldn't the higher-order computation arrive in the handler untouched by the scope machinery?

failing test for scoped with interpreter switch

---

README.md

This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113

README.md: update wiki

---

package.yaml
polysemy-plugin/package.yaml
polysemy-plugin/polysemy-plugin.cabal
polysemy.cabal

Just bumped bounds. Compiles locally with latest `Cabal` now. Not sure how your CI determines the used Cabal version.

Support Cabal 3.12.

---

package.yaml
polysemy-plugin/package.yaml
polysemy-plugin/polysemy-plugin.cabal
polysemy.cabal

The (possible) breaking change at
https://github.com/nomeata/inspection-testing/pull/81 shouldn't affect us.

Allow inspection-testing 0.6
